name: sqflite_date_table
description: Generates a date table for aggregation.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.0.6 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  handy_extensions:
    path: ../handy_extensions
  flutter:
    sdk: flutter
  intl: ^0.18.0
  sqflite: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
